---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    volumes:
      - "$MOLECULE_PROJECT_DIRECTORY/systemctl3.py:/usr/bin/systemctl"
  - name: ubuntu_latest
    image: docker.io/pycontribs/ubuntu:latest
    volumes:
      - "$MOLECULE_PROJECT_DIRECTORY/systemctl3.py:/usr/bin/systemctl"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
  - destroy
  - create
  - converge
  - verify
  - destroy