---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: netology
    image: docker.io/aragast/netology:latest
    pre_build_image: true
    volumes:
      - "$MOLECULE_PROJECT_DIRECTORY/systemctl3.py:/usr/bin/systemctl"
      - "$MOLECULE_PROJECT_DIRECTORY:/opt/vector-role"
    workdir: /opt/vector_role
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
  - destroy
  - create
  - converge
  - verify
  - destroy